apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: templates-client
  template:
    metadata:
      labels:
        app: templates-client
    spec:
      containers:
      - name: client-container
        imagePullPolicy: IfNotPresent
        image: image_client1
        ports:
        - containerPort: 3000


---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client-srv
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort