apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: image_comment: latest
          ports:
            - containerPort: 4001  # Port sur lequel votre application écoute
---
apiVersion: v1
kind: Service
metadata:
  name: comments-srv
spec:
  selector:
    app: comments
  ports:
    - protocol: TCP
      port: 80  # Port du service
      targetPort: 4001  # Port du conteneur
  type: LoadBalancer  # Utilisez NodePort ou ClusterIP si nécessaire
