apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-deployment
  labels:
    app: event-bus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: templates-eventbus
  template:
    metadata:
      labels:
        app: templates-eventbus
    spec:
      containers:
      - name: event-bus-container
        imagePullPolicy: IfNotPresent
        image: event-bus
        ports:
        - containerPort: 4005

---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-svr
spec:
  selector:
    app: event-bus
  ports:
    - protocol: TCP
      port: 4005 # Port du service
      targetPort: 4005 # Port du conteneur
  type: ClusterIP   

