apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-clusterip-deployment
  labels:
    app: posts-clusterip-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: templates-post
  template:
    metadata:
      labels:
        app: templates-post
    spec:
      containers:
      - name: posts-clusterip-container
        imagePullPolicy: IfNotPresent
        image: image_posts
        ports:
        - containerPort: 4000


---

apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: templates-post
  ports:
  - name: posts-clusterip-port
    protocol: TCP
    port: 4000
    targetPort: 4000